<a href="https://colab.research.google.com/github/BombasticOri/Bigdata_coolab/blob/main/practicaMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [41]:
# Crear un array unidimensional (vector) con 5 elementos enteros de tu elección
vector = np.array([1, 5, 10, 15, 20])
print("Array unidimensional:\n",vector)

# Crear una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos
matriz = np.arange(1, 10).reshape(3, 3)
print("Matriz bidimensional:\n",matriz)

# Crear una matriz de tamaño 2x4 llena de ceros
matriz_zeros = np.zeros((2, 4))
print("Matriz de tamaño 2x4:\n",matriz_zeros)

# Crear una matriz de tamaño 3x2 llena de unos
matriz_unos = np.ones((3, 2))
print("Matriz de tamaño 3x2:\n",matriz_unos)

# Crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10
matriz_random = np.random.randint(0, 11, (4, 4))
print("Matriz de tamaño 4x4:\n",matriz_random)

Array unidimensional:
 [ 1  5 10 15 20]
Matriz bidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz de tamaño 2x4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de tamaño 3x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matriz de tamaño 4x4:
 [[ 7 10 10  9]
 [ 1  0  5  8]
 [ 5  5  9  9]
 [ 7  0  5  9]]


In [18]:
# Acceder al tercer elemento del vector
tercer_elemento_vector = vector[2]
print("Tercer elemento del vector:", tercer_elemento_vector)

# Acceder al elemento en la segunda fila y segunda columna de la matriz
elemento_2_2_matriz = matriz[1, 1]
print("Elemento 2 fila y 2 columna:", elemento_2_2_matriz)

Tercer elemento del vector: 10
Elemento 2 fila y 2 columna: 5


In [21]:
# Verificar la cantidad de dimensiones de la matriz
dimensiones_matriz = matriz.ndim
print("Cantidad de dimensiones de la matriz:",dimensiones_matriz)

# Obtener la forma de la matriz
forma_matriz = matriz.shape
print("Forma de matriz:",forma_matriz)

# Obtener el tamaño total de la matriz
tamaño_matriz = matriz.size
print("Tamaño total de la matriz:",tamaño_matriz)

Cantidad de dimensiones de la matriz: 2
Forma de matriz: (3, 3)
Tamaño total de la matriz: 9


In [31]:
# Sumar dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10
matriz_aleatoria_1 = np.random.randint(0, 11, (2, 2))
matriz_aleatoria_2 = np.random.randint(0, 11, (2, 2))
suma_matrices = matriz_aleatoria_1 + matriz_aleatoria_2
print("Primera matriz aleatoria de 2x2:\n",matriz_aleatoria_1, "\n")
print("Segunda matriz aleatoria de 2x2:\n",matriz_aleatoria_2, "\n")
print("Suma de dos matrices 2x2:\n",suma_matrices,"\n")

# Multiplicar dos matrices de tamaño 3x2 y 2x3 respectivamente
matriz_3x2 = np.random.randint(0, 11, (3, 2))
matriz_2x3 = np.random.randint(0, 11, (2, 3))
multiplicacion_matrices = np.dot(matriz_3x2, matriz_2x3)
print("Primera matriz 3x2:\n",matriz_3x2, "\n")
print("Segunda matriz 2x3:\n",matriz_2x3, "\n")
print("Multiplicación de dos matrices 3x2 y 2x3:\n",multiplicacion_matrices,"\n")

# Dividir una matriz de tamaño 2x2 por otra matriz de tamaño 2x2
matriz_d1 = np.random.randint(1, 11, (2, 2))
matriz_d2 = np.random.randint(1, 11, (2, 2))
division_elementos = matriz_d1 / matriz_d2
division_inversa = np.dot(matriz_d1, np.linalg.inv(matriz_d2))
print("Primera matriz aleatoria de 2x2:\n",matriz_d1, "\n")
print("Segunda matriz aleatoria de 2x2:\n",matriz_d2, "\n")
print("Resultado de la división elementos de dos matrices 2x2:\n",division_elementos,"\n")
print("Resultado de la división inversa de dos matrices 2x2:\n",division_inversa)


Primera matriz aleatoria de 2x2:
 [[ 7 10]
 [ 1  1]] 

Segunda matriz aleatoria de 2x2:
 [[1 8]
 [3 7]] 

Suma de dos matrices 2x2:
 [[ 8 18]
 [ 4  8]] 

Primera matriz 3x2:
 [[9 0]
 [2 5]
 [1 7]] 

Segunda matriz 2x3:
 [[8 9 8]
 [2 9 7]] 

Multiplicación de dos matrices 3x2 y 2x3:
 [[72 81 72]
 [26 63 51]
 [22 72 57]] 

Primera matriz aleatoria de 2x2:
 [[7 3]
 [1 3]] 

Segunda matriz aleatoria de 2x2:
 [[4 4]
 [6 4]] 

Resultado de la división elementos de dos matrices 2x2:
 [[1.75       0.75      ]
 [0.16666667 0.75      ]] 

Resultado de la división inversa de dos matrices 2x2:
 [[-1.25  2.  ]
 [ 1.75 -1.  ]]


In [43]:
# Convertir el vector en una matriz de tamaño 2x3
matriz_conver = matriz.reshape(9, 1)
print("Matriz convertida:\n",matriz_conver,"\n")
# Convertir la matriz en un vector unidimensional
vector_matriz = matriz.flatten()
print("Matriz convertida en vector unidimensional:\n",vector_matriz)


Matriz convertida:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 

Matriz convertida en vector unidimensional:
 [1 2 3 4 5 6 7 8 9]


In [45]:
# Sumar todos los elementos de la matriz
suma_elementos_matriz = np.sum(matriz)
print("matriz:\n",matriz,"\n")
print("Suma de elementos de matriz:\n",suma_elementos_matriz,"\n")

# Calcular la media de cada fila de la matriz
media_filas_matriz = np.mean(matriz, axis=1)
print("matriz:\n",matriz,"\n")
print("Media de cada fila de matriz:\n",media_filas_matriz)


matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Suma de elementos de matriz:
 45 

matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Media de cada fila de matriz:
 [2. 5. 8.]


In [46]:
# Imprimir la primera fila de la matriz
primera_fila = matriz[0]
print("matriz:\n",matriz,"\n")
print("Primera fila de la matriz:\n",primera_fila,"\n")

# Imprimir las primeras dos columnas de la matriz
primeras_dos_columnas = matriz[:, :2]
print("matriz:\n",matriz,"\n")
print("Dos primeras columnas de la matriz:\n",primeras_dos_columnas,"\n")


matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Primera fila de la matriz:
 [1 2 3] 

matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Dos primeras columnas de la matriz:
 [[1 2]
 [4 5]
 [7 8]] 



In [51]:
# Definir una matriz de tamaño 4x4 con valores aleatorios
matriz_4x4 = np.random.randint(0, 101, (4, 4))
print("Matriz 4x4:\n",matriz_4x4,"\n")

# Encontrar el valor máximo y mínimo de la matriz, así como su posición
maximo_valor = np.max(matriz_4x4)
minimo_valor = np.min(matriz_4x4)
posicion_maximo_valor = np.unravel_index(np.argmax(matriz_4x4), matriz_4x4.shape)
posicion_minimo_valor = np.unravel_index(np.argmin(matriz_4x4), matriz_4x4.shape)
print("Valor maximo:\n",maximo_valor,"\n","\n Posicion del valor maximo:\n",posicion_maximo_valor,"\n")
print("Valor minimo:\n",minimo_valor,"\n","\n Posicion del valor minimo:\n",posicion_minimo_valor)



Matriz 4x4:
 [[78 71 37 45]
 [92 76 98 39]
 [22 45 91  8]
 [83 94 39 71]] 

Valor maximo:
 98 
 
 Posicion del valor maximo:
 (1, 2) 

Valor minimo:
 8 
 
 Posicion del valor minimo:
 (2, 3)
